fix error when open scene or switch to another scene
## Error message on console ##
```
no access to ID:18723
ERROR: FileAccessWindows::_get_modified_time: Method/Function Failed, returning: 0
   At: drivers\windows\file_access_windows.cpp:251
```