Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in a39e0346f9f055ca68cb7e307442ca15a0850301,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```