fix crash and error with texture atlas
- crashes at Project Export Settings > Preview Atlas
- error message when export project

```
ERROR: EditorImportExport::get_import_plugin_by_name: Condition ' !by_idx.has(p_string) ' is true. returned: Ref<EditorImportPlugin>()
   At: tools\editor\editor_import_export.cpp:1548
```

it is caused by https://github.com/godotengine/godot/commit/a70eb86cf8744cb4c259ce3c23a4e345078bfc97#diff-67a74bd708380c6b3baa717bb178dd47R802